### ISSUE TITLE
Primary TODO List

### ISSUE THREAD

**Issue by InjuredWolf** [InjuredWolf/NovemScientia#1]
In no particular order (some tasks will obviously be done earlier than others)

- [ ] Base Mod Framework

- [ ] Materials, ores, etc.

- [ ] Energy System (We're not using RF)

- [ ] Entire Research Framework

- [ ] Each of the 9 Sciences (Designed to an extent) - Physics, Meteorology (Weather), Chemistry, Astronomy, Arcanology (fancy magic system), Chronology (Time), Geology (with Archeology thrown in), Biology (with some Psychology), Robotics (May be replaced by something else if someone has any suggestions?)

- [ ] Tree Falling (!)

- [ ] Moss Spreading, Burning, etc.

- [ ] Stamina, Body stats, Hydration, Temperature, Sleep, Sanity, etc.

- [ ] Weather and Climate, Seasons

- [ ] Genetics, Diseases and such

- [ ] Block Force Thresholds (may be scrapped due to potential lag on large servers, we shall see - config option?)

- [ ] Aura and magic system

- [ ] Spirit Realm mechanics

- [ ] Contributor bonuses (might include Patreon bonuses too)

- [ ] Kaiken Loppu (Finnish: "End of Everything")

- [ ] Plants and stuff

- [ ] Planets, Space

- [ ] Mod compat & Integration

- [ ] Machines, Tech Progression

- [ ] Emotions? Friend/Enemy system?

- [ ] Equippables

- [ ] Modular Tools, Armour, etc.

- [ ] Antimatter

- [ ] Inventory and weight system

- [ ] Block Physics

- [ ] Vertical Chunks and realistic world height?

- [ ] Speed-based Fall damage, proper gravity, terminal velocity

- [ ] Elements and radioactive decay
